### ISSUE TITLE
请问有没有将.obj文件形成动画的代码

### ISSUE THREAD

**Issue by anzisheng** [boycehbz/DMMR#10]
你好，我看你在viz_camras.py文件中，只显示了一帧图片中的人物smpl模型，请问有没有连续显示多帧中模型构成动画的代码？

**Comment by boycehbz** [comment]
你可以加一个循环。不过鉴于加载obj的速度，我建议你加载拟合的SMPL参数，通过SMPL的前向函数得到mesh来显示。

**Comment by anzisheng** [comment]
你好，不过没查到用来清屏擦掉上一帧的函数是哪一个？

**Comment by boycehbz** [comment]
循环里更新顶点和法向位置，不要add_geometry。具体可以参考open3D API
