### ISSUE TITLE
能不能看一下你的write_json函数

### ISSUE THREAD

**Issue by anzisheng** [boycehbz/DMMR#11]
我发现我使用AlphaPose得到的shelf文件和你给的shelf数据主要不同在于：
1. 我发现你的keypints文件中有的people的pose_keypoints_2d 是设置为null的，但是我怎么能知道应该是哪个people的pose_keypoints_2d 应设置为null呢？就是如何规定每个人的顺序呢？比如，我在00300.keypoints.json中发现四个人中，0和2是有数据的，1和3的关节数据为null，如何认定哪个人是0 或1 呢？我安装位置顺序设定的吗？

**Comment by anzisheng** [comment]
请问：你是使用的你在论文中提到的【66】“Omni-scale feature learning for person re-identification”得到追踪结果的吗？人物个数需要提前设定的吗？

**Comment by boycehbz** [comment]
> 

是的，tracking完做滤除

**Comment by anzisheng** [comment]
请问一下，第一帧的时候，我为什么会保留0号和2号人物，而丢掉1号和3号人物呢？第一帧之前也没有先验来告知他们的信息，应该滤除掉哪一个。

**Comment by boycehbz** [comment]
第一帧是query

**Comment by anzisheng** [comment]
“第一帧是query”：我不明白的地方是第一帧只得到两个人物，他们的编号不应该是0和1吗？怎么知道后面会有比1号置信度高的2号呢？能不能把你fork的“Omni-scale feature learning for person re-identification”的代码参考一下？

**Comment by boycehbz** [comment]
跟人的编号没关系，任意一个人都可以是0号。

**Comment by anzisheng** [comment]
那现在取得2D关节数据的流程就是使用了AlphaPose+OsNet？AlphaPose部分做检测，然后把检测框送到OsNet进行追踪？我的理解对吗？

**Comment by boycehbz** [comment]
是的

**Comment by anzisheng** [comment]
那这两部分如何结合使用呢？有示例代码吗？AlphaPose 不是也可以做tracker吗？如果使用AlphaPose的tracker进行追踪会有不同吗？

**Comment by boycehbz** [comment]
alphapose里面用的就是“Omni-scale feature learning for person re-identification”。你可以用alphapose的tracking结果试试。我们现在的这个方法对tracking的依赖还是挺高的，tracking的质量非常差的话可能会滤不掉。我们在后续的工作里把tracking用一个association来代替了，过一段时间会更新到这个仓库里。

**Comment by anzisheng** [comment]
如何把AlphaPose和OsNe一起使用？我看这方面的资料比较少，能给点提示吗？
