### ISSUE TITLE
如何得到正确的keypoints.json数据

### ISSUE THREAD

**Issue by anzisheng** [boycehbz/DMMR#12]
你好，我在处理shelf数据集的时候，第一张图片00300.jpg，我看到图片中只有两个人，并且我使用你forked AlphaPose-boycehbz 进行检测及追踪的时候，得到的00300_keypoints.json文件也显示有两个“pose_keypoints_2d”。
![Screenshot from 2022-09-02 13-54-21](https://user-images.githubusercontent.com/16410690/188068258-48daec22-9afa-446b-a7ec-cf644c996bbf.png)
如果在fit_smpl.yaml中设置num_people为 2 的话，只能显示两个人的模型。如果设置num_people: 4的话，程序运行不通过。
我看你的00300_keypoints.json，里面存在4个“pose_keypoints_2d”数据【两个有数值，两个null】
![Screenshot from 2022-09-02 14-01-03](https://user-images.githubusercontent.com/16410690/188069130-7129c259-b698-47a0-8529-53e58789c610.png)
我想请问你是如何修改AlphaPose得到这个数据的？

**Comment by boycehbz** [comment]
目前这个得要求总人数已知，没有被检测到的补None

**Comment by anzisheng** [comment]
我把不足的人数补足为None之后，这样json文件后面会有连续的多个null。但是得到的显示结果也不好。 我看你的数据null是分散的，得到的结果挺好的。这是怎么回事呢？

**Comment by boycehbz** [comment]
根据tracking的结果，同一个人放在people列表里的序号是固定的。比如tracking得到的0号人，都放在people列表的第一个位置，中间如果有没检测上的话存None。每个人在每帧people列表中的位置都是固定的。感谢你的提醒，之后我把这个association的也加进来。

**Comment by anzisheng** [comment]
按照你的说法，是不是我需要看完整个视频之后才能固定每个人的序号，这样也不适合摄像头实时拍摄人数变化的地方？

**Comment by boycehbz** [comment]
如果你不要求估计相机参数的话 现在的filtering其实可以用来做cross-view association，这样就不需要tracking来确定人的序号了。但是你想实现实时拍摄人数变化的情况还是需要一些工程上的优化的，比如新出现的人给新的tracklet，这个目前在这个项目里是没有考虑的。
