### ISSUE TITLE
How can we get the labels of MHHI dataset?

### ISSUE THREAD

**Issue by ZhenyuX1E** [boycehbz/DMMR#15]
I cannot find the original dataset resource. It seems that the dataset is not completely public?

**Comment by boycehbz** [comment]
The dataset is provided by its authors [TPAMI2013](https://ieeexplore.ieee.org/abstract/document/6468043/). You may require to email them for requesting the download link.

**Comment by ZhenyuX1E** [comment]
Thanks!
