### ISSUE TITLE
How to visualize the grid picture？

### ISSUE THREAD

**Issue by HonglinChu** [boycehbz/DMMR#19]
Thanks for your work，I run viz_cameras.py
![image](https://github.com/boycehbz/DMMR/assets/11087575/80d4160f-1cef-4f53-9f6c-abccd8ce6ddf)

how to show image with grid
![image](https://github.com/boycehbz/DMMR/assets/11087575/d8d40180-b0bf-4715-81c0-54b09413fd8f)

**Comment by HonglinChu** [comment]
and how to determine the ground plane？

**Comment by boycehbz** [comment]
For calibrated cameras, the ground plane can be directly visualized with Open3D using plane parameters. For uncalibrated cases, you can estimate ground plane parameters by fitting 3D ankle keypoints.

**Comment by zmhsmart** [comment]
Can you provide the implementation code and provide learning? Thank you very much. It is very important to me.
