### ISSUE TITLE
viz_cameras nothing show

### ISSUE THREAD

**Issue by skyhe1410** [boycehbz/DMMR#2]
i run "python viz_cameras.py",but shows nothing. I found the folder "output" doesn't have "output\cameras".

**Comment by skyhe1410** [comment]
i run code on ubuntu 20.04, thanks.

**Comment by boycehbz** [comment]
Thanks for your interest! I can successfully obtain the output camera file by running "python main.py --config cfg_files/fit_smpl.yaml" on my machine.
You can check whether the --opt_cam is true in the configuration file.
If you still have the problem, please contact with me. I will check the code in detail.

**Comment by skyhe1410** [comment]
thank you very much for your reply @boycehbz
According to your advice, I checked the --opt_cam which shows true, but there is still noting to show. Need your help again! Thanks!

**Comment by boycehbz** [comment]
Sorry for the mistake. The path of the output camera file in viz_camera.py is incorrect for the current code, which should be "output/camparams/doubleB/00064.txt". I have revised the code. You can pull the latest code and check it again.

**Comment by skyhe1410** [comment]
thank you very much for your reply @boycehbz
But I don't have any 3D models except a few cameras in my window

**Comment by boycehbz** [comment]
I have added a sample for the mesh visualization in viz_cameras.py. You can modify the code for visualizing more results.

**Comment by skyhe1410** [comment]
thank you very much @boycehbz

**Comment by skyhe1410** [comment]
Can you share the complete code for playing 3d animation in your demo video. Thank you very much. @boycehbz

**Comment by boycehbz** [comment]
The demo video is rendered by private rendering codes. I guess the Open3D can also obtain the same results, but it may exist minor differences for the mesh visualization.
