### ISSUE TITLE
how to make my own data in step 2

### ISSUE THREAD

**Issue by skyhe1410** [boycehbz/DMMR#3]
hello.thank you very much for your work. how to make my own data in step 2.

**Comment by boycehbz** [comment]
You can detect the 2D poses using AlphaPose with halpe format (https://github.com/MVIG-SJTU/AlphaPose/blob/master/docs/MODEL_ZOO.md) and calibrate the intrinsic camera parameter using OpenCV (A proximate intrinsic parameter may also work). Finally, put the data in the corresponding folder.

**Comment by skyhe1410** [comment]
thank you @boycehbz
