### ISSUE TITLE
pose json version

### ISSUE THREAD

**Issue by skyhe1410** [boycehbz/DMMR#4]
In the json file of 2d pose, my version is ‘alphapose v0.3', but why is '1.1' in yours. my alphapose code is the latest on github.

**Comment by boycehbz** [comment]
it doesn't matter

**Comment by skyhe1410** [comment]
However, the number of pose data in the same picture will be less than yours. I will report an error when I run it.

**Comment by skyhe1410** [comment]
![1648096793(1)](https://user-images.githubusercontent.com/17879968/159843601-8bb06397-0432-4b91-b245-527ed416296d.png)

**Comment by boycehbz** [comment]
You can detect the 2D pose using AlphaPose with **halpe format**. It contains 26 keypoints.

**Comment by boycehbz** [comment]
For example

```python scripts/demo_inference.py --cfg configs/halpe_26/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/halpe26_fast_res50_256x192.pth --indir examples/demo/ --save_img```

**Comment by skyhe1410** [comment]
ok, thank you. @boycehbz

**Comment by skyhe1410** [comment]
I tried your method,but i still reported an error.please help me. thank you. @boycehbz
![](https://user-images.githubusercontent.com/17879968/159843601-8bb06397-0432-4b91-b245-527ed416296d.png)

**Comment by skyhe1410** [comment]
I found that your JSON data has 78 values, but mine has only 54
![1648113302(1)](https://user-images.githubusercontent.com/17879968/159883036-57d13467-5d36-4ed1-a81e-cdd2b6b2ee73.png)
![1648113302](https://user-images.githubusercontent.com/17879968/159883045-f4054a5d-095a-40de-924e-ceae7999674b.png)

.

**Comment by boycehbz** [comment]
You may use an improper AlphaPose command. You can try to save the detected pose with the same format as my demo data.

**Comment by skyhe1410** [comment]
Thank you for your reply. The alphapose command I used is correct and the result format is correct, but the data is less than yours.
 @boycehbz

**Comment by JACKYLUO1991** [comment]
@skyhe1410 我和你的问题是一样的，v0.3版本给出的少于作者的点位数量，请问你是如何解决的？

**Comment by boycehbz** [comment]
https://github.com/boycehbz/AlphaPose/blob/master/getData-image-halpe-track.sh
这边有一个我fork的alphapose，这个脚本估计的结果拆分后，跟我用的是一样的

**Comment by JACKYLUO1991** [comment]
@boycehbz 我觉得是我用了--format参数导致以OpenPose格式输出的原因
