### ISSUE TITLE
How to get the motionprior_hp.pkl from my own data

### ISSUE THREAD

**Issue by anzisheng** [boycehbz/DMMR#5]
我发现在你的数据文件中有一个”motionprior_hp.pkl“，请问使用自己的数据，我怎么才能得到这个文件？

**Comment by boycehbz** [comment]
这个是运动先验的权重。如果想要自己构建的话，可以用你自己的数据训练[MotionVAE_HP.py](https://github.com/boycehbz/DMMR/blob/main/core/model/MotionVAE_HP.py)这个模型，最后将模型权重导出。

**Comment by anzisheng** [comment]
谢谢回复，请问一下，训练这个模型是不是只能用自己的数据训练，没有公共的数据集可以使用？

**Comment by boycehbz** [comment]
所有带SMPL motion的数据都可以，目前这个是用AMASS训练的

**Comment by anzisheng** [comment]
然后需要迁移到自己的数据上去吗？

**Comment by boycehbz** [comment]
不需要

**Comment by anzisheng** [comment]
有个问题，我使用的是h36m的数据你给的这个motionprior_hp.pkl，进行预测，得到的transl的值特别大，都是一两千左右，这是为什么呢？我改如何调整呢？

**Comment by boycehbz** [comment]
带相机参数优化吗？如果不优化相机，是否可能是你的相机参数外参平移不是米制单位的？

**Comment by anzisheng** [comment]
果然如此，谢谢提醒。

**Comment by anzisheng** [comment]
@boycehbz 还有一个问题要问你，我调整了摄像机的平移参数之后，位置还可以，但是还原的mesh特别诡异，不成人样了，我改从什么地方查原因呢？

**Comment by boycehbz** [comment]
[init_guess.py](https://github.com/boycehbz/DMMR/blob/main/core/utils/init_guess.py) L213 改成True 可以看下初始化的结果对不对。如果人体全局位置差的很大的话 可能相机参数是有问题的

**Comment by anzisheng** [comment]
@boycehbz 你好，这边照相机的参数问题。请问你那边能给一下，shelf或campus数据集的测试数据吗？能否邮箱anzisheng@163.com？

**Comment by anzisheng** [comment]
你好， 我把 init_guess.py L213 改成True之后，人物模型到不是乱的，不过 显示的模型显得特别大，是横着的， 请问我改调整那个照相机参数？ 我使用的是shelf数据集的照相机。
