### ISSUE TITLE
“cannot convert float NaN to integer”

### ISSUE THREAD

**Issue by anzisheng** [boycehbz/DMMR#8]
当我使用自己的数据，执行fitting的时候，遇到一个错误如下：
执行 `loss_dict['reproj'] += int(joint_loss.data)`的时候，报错错误：
`ValueError: cannot convert float NaN to integer`
我想问一下，开始是我的数据在那个方面不合适导致 nan？

**Comment by boycehbz** [comment]
这个问题需要结合具体数据，你可以debug一下重投影loss里面的投影过程，检查相机、2D pose是否有问题
