### ISSUE TITLE
我得到的结果模型人物比较小，是和照相机的参数有关吗？

### ISSUE THREAD

**Issue by anzisheng** [boycehbz/DMMR#9]
你好，我多shelf数据集进行了测试，得到的结果的人物模型比较小，请问是和照相机参数有关吗？
![img_000000](https://user-images.githubusercontent.com/16410690/185850960-b6b3d940-b7bf-435b-bae7-e11efaa81e44.png)

**Comment by boycehbz** [comment]
我也不能确定你的是什么问题。我截了一段shelf的数据，你可以试一试。
链接：https://pan.baidu.com/s/11wOUdhoQ9a0sM1fsk4oWpA?pwd=g3mu 
提取码：g3mu
